# Generated by Django 5.1.2 on 2024-11-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Games",
            fields=[
                ("game_id", models.AutoField(primary_key=True, serialize=False)),
                ("game_name", models.CharField(max_length=255)),
                ("game_platform", models.CharField(max_length=255)),
                ("game_rating", models.DecimalField(decimal_places=1, max_digits=3)),
                ("game_cover", models.URLField(max_length=500)),
            ],
        ),
    ]
