# Generated by Django 5.1.2 on 2024-12-06 11:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Developer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="开发厂商"
                    ),
                ),
            ],
            options={
                "verbose_name": "开发厂商",
                "verbose_name_plural": "开发厂商列表",
            },
        ),
        migrations.CreateModel(
            name="GameType",
            fields=[
                ("type_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type_name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="类型名称"
                    ),
                ),
            ],
            options={
                "verbose_name": "游戏类型",
                "verbose_name_plural": "游戏类型列表",
            },
        ),
        migrations.CreateModel(
            name="Games",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "game_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="实际的游戏id"
                    ),
                ),
                (
                    "game_name",
                    models.CharField(max_length=255, verbose_name="游戏名称"),
                ),
                (
                    "game_platform",
                    models.CharField(max_length=255, verbose_name="游戏平台"),
                ),
                (
                    "game_rating",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                        verbose_name="游戏评分",
                    ),
                ),
                (
                    "game_cover",
                    models.URLField(max_length=500, verbose_name="游戏封面 URL"),
                ),
                (
                    "game_description",
                    models.TextField(
                        default="Default game description",
                        max_length=500,
                        verbose_name="游戏描述",
                    ),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.developer",
                        verbose_name="开发厂商",
                    ),
                ),
            ],
            options={
                "verbose_name": "游戏",
                "verbose_name_plural": "游戏列表",
            },
        ),
        migrations.CreateModel(
            name="GameComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_rating",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                        verbose_name="用户评分",
                    ),
                ),
                ("comment", models.TextField(max_length=1000, verbose_name="评论内容")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="评论时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.games",
                        verbose_name="游戏",
                    ),
                ),
            ],
            options={
                "verbose_name": "游戏评论",
                "verbose_name_plural": "游戏评论列表",
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "developers",
                    models.ManyToManyField(
                        blank=True, to="home.developer", verbose_name="开发厂商偏好"
                    ),
                ),
                (
                    "game_types",
                    models.ManyToManyField(
                        blank=True, to="home.gametype", verbose_name="游戏类型偏好"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户偏好",
                "verbose_name_plural": "用户偏好列表",
            },
        ),
        migrations.CreateModel(
            name="GameTypeRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_type_relations",
                        to="home.games",
                        verbose_name="游戏",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_game_relations",
                        to="home.gametype",
                        verbose_name="类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "游戏类型关系",
                "verbose_name_plural": "游戏类型关系列表",
                "unique_together": {("game", "type")},
            },
        ),
    ]
