# Generated by Django 5.1.2 on 2024-11-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="games",
            old_name="game_cover",
            new_name="cover",
        ),
        migrations.RenameField(
            model_name="games",
            old_name="game_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="games",
            old_name="game_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="games",
            old_name="game_platform",
            new_name="platform",
        ),
        migrations.RenameField(
            model_name="games",
            old_name="game_rating",
            new_name="rating",
        ),
    ]
