# Generated by Django 5.1.2 on 2024-12-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamecomment",
            name="game_actual_id",
            field=models.CharField(
                default=0, max_length=255, verbose_name="游戏实际ID"
            ),
        ),
    ]
