# Generated by Django 5.1.2 on 2024-11-15 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_rename_game_cover_games_cover_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="games",
            old_name="cover",
            new_name="game_cover",
        ),
        migrations.RenameField(
            model_name="games",
            old_name="id",
            new_name="game_id",
        ),
        migrations.RenameField(
            model_name="games",
            old_name="name",
            new_name="game_name",
        ),
        migrations.RenameField(
            model_name="games",
            old_name="platform",
            new_name="game_platform",
        ),
        migrations.RenameField(
            model_name="games",
            old_name="rating",
            new_name="game_rating",
        ),
        migrations.AddField(
            model_name="games",
            name="game_description",
            field=models.TextField(default="Default game description", max_length=500),
        ),
        migrations.CreateModel(
            name="GameRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.DecimalField(decimal_places=1, max_digits=3)),
                ("comment", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.games"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
