# Generated by Django 5.1.2 on 2024-11-15 13:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_rename_cover_games_game_cover_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GameRating",
            new_name="GameComment",
        ),
    ]
