# Generated by Django 5.1.2 on 2024-11-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_rename_gamerating_gamecomment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamecomment",
            name="rating",
        ),
        migrations.AddField(
            model_name="gamecomment",
            name="is_recommended",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
