# Generated by Django 5.1.2 on 2024-11-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_gamecomment_rating_gamecomment_is_recommended"),
    ]

    operations = [
        migrations.AddField(
            model_name="games",
            name="game_type",
            field=models.CharField(default="Default game type", max_length=64),
        ),
    ]
