# Generated by Django 5.1.2 on 2024-11-19 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_games_game_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("tag_id", models.AutoField(primary_key=True, serialize=False)),
                ("tag_name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="games",
            name="game_type",
        ),
        migrations.CreateModel(
            name="Game_Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.games"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.tag"
                    ),
                ),
            ],
            options={
                "unique_together": {("game", "tag")},
            },
        ),
    ]
