# Generated by Django 5.1.2 on 2024-11-19 07:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_tag_remove_games_game_type_game_tag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Developer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="开发厂商"
                    ),
                ),
            ],
            options={
                "verbose_name": "开发厂商",
                "verbose_name_plural": "开发厂商列表",
            },
        ),
        migrations.CreateModel(
            name="GameType",
            fields=[
                ("type_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tag_name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="类型名称"
                    ),
                ),
            ],
            options={
                "verbose_name": "游戏类型",
                "verbose_name_plural": "游戏类型列表",
            },
        ),
        migrations.AlterModelOptions(
            name="gamecomment",
            options={"verbose_name": "游戏评论", "verbose_name_plural": "游戏评论列表"},
        ),
        migrations.AlterModelOptions(
            name="games",
            options={"verbose_name": "游戏", "verbose_name_plural": "游戏列表"},
        ),
        migrations.AlterUniqueTogether(
            name="gamecomment",
            unique_together={("user", "game")},
        ),
        migrations.AddField(
            model_name="gamecomment",
            name="user_rating",
            field=models.DecimalField(
                decimal_places=1,
                default=0.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
                verbose_name="用户评分",
            ),
        ),
        migrations.AlterField(
            model_name="gamecomment",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="评论内容"),
        ),
        migrations.AlterField(
            model_name="gamecomment",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="home.games",
                verbose_name="游戏",
            ),
        ),
        migrations.AlterField(
            model_name="gamecomment",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="评论时间"),
        ),
        migrations.AlterField(
            model_name="gamecomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="games",
            name="game_cover",
            field=models.URLField(max_length=500, verbose_name="游戏封面 URL"),
        ),
        migrations.AlterField(
            model_name="games",
            name="game_description",
            field=models.TextField(
                default="Default game description",
                max_length=500,
                verbose_name="游戏描述",
            ),
        ),
        migrations.AlterField(
            model_name="games",
            name="game_name",
            field=models.CharField(max_length=255, verbose_name="游戏名称"),
        ),
        migrations.AlterField(
            model_name="games",
            name="game_platform",
            field=models.CharField(max_length=255, verbose_name="游戏平台"),
        ),
        migrations.AlterField(
            model_name="games",
            name="game_rating",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
                verbose_name="游戏评分",
            ),
        ),
        migrations.CreateModel(
            name="GameTypeRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.games",
                        verbose_name="游戏",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.gametype",
                        verbose_name="类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "游戏类型关系",
                "verbose_name_plural": "游戏类型关系列表",
                "unique_together": {("game", "type")},
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.developer",
                        verbose_name="开发厂商",
                    ),
                ),
                (
                    "game_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.gametype",
                        verbose_name="游戏类型",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户偏好",
                "verbose_name_plural": "用户偏好列表",
            },
        ),
        migrations.DeleteModel(
            name="Game_Tag",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.RemoveField(
            model_name="gamecomment",
            name="is_recommended",
        ),
    ]
