# Generated by Django 5.1.2 on 2024-11-19 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_developer_gametype_alter_gamecomment_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gametype",
            old_name="tag_name",
            new_name="type_name",
        ),
    ]
