# Generated by Django 5.1.2 on 2024-11-19 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_rename_tag_name_gametype_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gametyperelation",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_type_relations",
                to="home.games",
                verbose_name="游戏",
            ),
        ),
        migrations.AlterField(
            model_name="gametyperelation",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="type_game_relations",
                to="home.gametype",
                verbose_name="类型",
            ),
        ),
    ]
