# Generated by Django 5.1.2 on 2024-11-19 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_gametyperelation_game_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="games",
            name="developer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="home.developer",
                verbose_name="开发厂商",
            ),
        ),
    ]
