# Generated by Django 5.1.2 on 2024-11-19 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_games_developer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreference",
            name="developer",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="game_type",
        ),
        migrations.AddField(
            model_name="userpreference",
            name="developers",
            field=models.ManyToManyField(
                blank=True, to="home.developer", verbose_name="开发厂商偏好"
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="game_types",
            field=models.ManyToManyField(
                blank=True, to="home.gametype", verbose_name="游戏类型偏好"
            ),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
